In [1]:
from numpy import select
import pandas as pd
import duckdb
pd.set_option('display.max_columns', None)

chemin_fichier = r"retailcorps.parquet"

df=duckdb.query(f"""
    select distinct *
    From read_parquet('{chemin_fichier}')
""").df()

In [2]:
def explorer_dataset(dataset):
        print(f"Start {'-'*10} Pour ce dataset, la taille est de {dataset.shape} {'-'*10}")
        print('-'*30)
        display(dataset.head(3))
        print('-'*30)
        display(dataset.tail(3))
        print('-'*30)
        print(f"Présences de valeurs 'NaN'.")
        print(f"{dataset.isna().sum()}")
        display(dataset[dataset.isna().any(axis=1)])
        print('-'*30)
        print(f"Les doublons")
        print(f"{dataset.duplicated().sum()}")
        print('-'*30)
        print(f"Les types de données")
        print(f"{dataset.dtypes}")
        print('-'*30)
        print(f"Description")
        display(dataset.describe().T)
        print("FIN"+'-'*100)

In [ ]:
explorer_dataset(df)

Start ---------- Pour ce dataset, la taille est de (1067371, 27) ----------
------------------------------

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,ProductFamily,ProductNameClean,UnitPriceGBP,UnitCostGBP,CustomerSegment,CustomerType,LoyaltyProgram,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
0,611407,543530,90214A,"LETTER ""A"" BLING KEY RING",1,2011-02-09 12:46:00,NaN,United Kingdom,OTHER,Other,Other,"Letter ""A"" Bling Key Ring",12.13,7.69,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,SPRING,0.05,Completed,2,Europe,Western Europe,GBP
1,611447,543532,22467,GUMBALL COAT RACK,1,2011-02-09 12:59:00,NaN,United Kingdom,OTHER,Other,Other,Gumball Coat Rack,14.8,8.35,VIP,Retailer,Gold,Phone,Invoice,WH-UK-02,NONE,0.0,Completed,7,Europe,Western Europe,GBP
2,611589,543535,22667,RECIPE BOX RETROSPOT,6,2011-02-09 13:37:00,17537.0,United Kingdom,OTHER,Other,Other,Recipe Box Retrospot,4.14,2.21,Loyal,Small business,Silver,Store,Bank transfer,WH-UK-01,SPRING,0.05,Completed,4,Europe,Western Europe,GBP

------------------------------

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,ProductFamily,ProductNameClean,UnitPriceGBP,UnitCostGBP,CustomerSegment,CustomerType,LoyaltyProgram,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
1067368,122195,501080,21865,PINK UNION JACK PASSPORT COVER,1,2010-03-12 11:19:00,NaN,United Kingdom,OTHER,Other,Other,Pink Union Jack Passport Cover,6.96,2.7,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP
1067369,122254,501080,22348,TEA BAG PLATE RED SPOTTY,2,2010-03-12 11:19:00,NaN,United Kingdom,KITCHEN,Kitchenware,Interior,Tea Bag Plate Red Spotty,9.65,5.67,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP
1067370,122284,501080,35004C,SET OF 3 COLOURED FLYING DUCKS,1,2010-03-12 11:19:00,NaN,United Kingdom,OTHER,Other,Other,Set Of 3 Coloured Flying Ducks,14.62,8.13,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP

------------------------------
Présences de valeurs 'NaN'.
OrderLineID                 0
Invoice                     0
StockCode                   0
Description             12934
Quantity                    0
InvoiceDate                 0
CustomerID             252975
Country                     0
ProductCategoryCode      3210
ProductCategory          4324
ProductFamily               0
ProductNameClean         4382
UnitPriceGBP                0
UnitCostGBP              1039
CustomerSegment             0
CustomerType                0
LoyaltyProgram              0
SalesChannel             4178
PaymentMethod               0
WarehouseID              1767
PromotionCode            1764
DiscountRate              635
OrderStatus              1327
DeliveryTime              806
Continent                   0
Region                      0
Currency                 1666
dtype: int64

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,ProductFamily,ProductNameClean,UnitPriceGBP,UnitCostGBP,CustomerSegment,CustomerType,LoyaltyProgram,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
0,611407,543530,90214A,"LETTER ""A"" BLING KEY RING",1,2011-02-09 12:46:00,NaN,United Kingdom,OTHER,Other,Other,"Letter ""A"" Bling Key Ring",12.13,7.69,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,SPRING,0.05,Completed,2,Europe,Western Europe,GBP
1,611447,543532,22467,GUMBALL COAT RACK,1,2011-02-09 12:59:00,NaN,United Kingdom,OTHER,Other,Other,Gumball Coat Rack,14.8,8.35,VIP,Retailer,Gold,Phone,Invoice,WH-UK-02,NONE,0.0,Completed,7,Europe,Western Europe,GBP
3,611817,543546,21294,ETCHED GLASS COASTER,6,2011-02-09 16:52:00,NaN,United Kingdom,OTHER,Other,Other,Etched Glass Coaster,9.86,3.5,VIP,Retailer,Gold,Online,Card,WH-UK-01,NONE,0.0,Completed,8,Europe,Western Europe,GBP
4,611913,543546,84279B,CHERRY BLOSSOM DECORATIVE FLASK,1,2011-02-09 16:52:00,NaN,United Kingdom,OTHER,Other,Other,Cherry Blossom Decorative Flask,12.66,7.15,VIP,Retailer,Gold,Online,Card,WH-UK-01,NONE,0.0,Completed,8,Europe,Western Europe,GBP
13,612470,543629,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2011-02-10 15:55:00,NaN,United Kingdom,KITCHEN,Kitchenware,Interior,Set 2 Tea Towels I Love London,22.88,11.03,VIP,Retailer,Gold,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,7,Europe,Western Europe,GBP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1067366,122177,501080,21578,WOODLAND DESIGN COTTON TOTE BAG,1,2010-03-12 11:19:00,NaN,United Kingdom,HOME,Home decoration,Interior,Woodland Design Cotton Tote Bag,21.76,10.46,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP
1067367,122193,501080,21846,PINK DIAMANTE PEN IN GIFT BOX,1,2010-03-12 11:19:00,NaN,United Kingdom,GIFT,Gifts,Occasions,Pink Diamante Pen In Gift Box,7.89,"2,86",VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP
1067368,122195,501080,21865,PINK UNION JACK PASSPORT COVER,1,2010-03-12 11:19:00,NaN,United Kingdom,OTHER,Other,Other,Pink Union Jack Passport Cover,6.96,2.7,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP
1067369,122254,501080,22348,TEA BAG PLATE RED SPOTTY,2,2010-03-12 11:19:00,NaN,United Kingdom,KITCHEN,Kitchenware,Interior,Tea Bag Plate Red Spotty,9.65,5.67,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP
1067370,122284,501080,35004C,SET OF 3 COLOURED FLYING DUCKS,1,2010-03-12 11:19:00,NaN,United Kingdom,OTHER,Other,Other,Set Of 3 Coloured Flying Ducks,14.62,8.13,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP

------------------------------
Les doublons
0
------------------------------
Les types de données
OrderLineID            str
Invoice                str
StockCode              str
Description            str
Quantity               str
InvoiceDate            str
CustomerID             str
Country                str
ProductCategoryCode    str
ProductCategory        str
ProductFamily          str
ProductNameClean       str
UnitPriceGBP           str
UnitCostGBP            str
CustomerSegment        str
CustomerType           str
LoyaltyProgram         str
SalesChannel           str
PaymentMethod          str
WarehouseID            str
PromotionCode          str
DiscountRate           str
OrderStatus            str
DeliveryTime           str
Continent              str
Region                 str
Currency               str
dtype: object
------------------------------
Description

,count,unique,top,freq
OrderLineID,1067371,1067371,611407,1
Invoice,1067371,53628,537434,1350
StockCode,1067371,5619,85123A,5776
Description,1054437,9081,WHITE HANGING HEART T-LIGHT HOLDER,5776
Quantity,1067371,1150,1,292698
InvoiceDate,1067371,55180,2010-12-06 16:57:00,1332
CustomerID,814396,5942,17841.0,12947
Country,1067371,61,United Kingdom,969892
ProductCategoryCode,1064161,7,OTHER,451026
ProductCategory,1063047,14,Other,448331
ProductFamily,1067371,4,Other,452379
ProductNameClean,1062989,5620,White Hanging Heart T-Light Holder,5918
UnitPriceGBP,1067371,4348,14.47,6039
UnitCostGBP,1066332,2611,7.81,7618
CustomerSegment,1067371,4,VIP,447028
CustomerType,1067371,3,Retailer,529270
LoyaltyProgram,1067371,4,Gold,447028
SalesChannel,1063193,4,Marketplace,270563
PaymentMethod,1067371,4,PayPal,271614
WarehouseID,1065604,9,WH-UK-01,492799
PromotionCode,1065607,5,SPRING,221792
DiscountRate,1066736,6,0.05,221802
OrderStatus,1066044,3,Completed,937812
DeliveryTime,1066565,19,15,75869
Continent,1067371,6,Europe,1062492
Region,1067371,11,Western Europe,1049690
Currency,1065705,15,GBP,983751

FIN----------------------------------------------------------------------------------------------------

Dans la table df_product (18 284 lignes) :

Colonne "StockCode"
    - Aucune valeure nulle

Colonne "ProductCategory"
    - 2017 valeurs nulles

Colonne "ProductCategoryCode"
    - 1762 valeurs nulles
=> Les colonnes "ProductCategory" et "ProductCategoryCode" sont redondants : On va créer une colonne ProductCategory_Clean qui sera une combinaison des deux

Colonne "ProductFamily"
    - Aucune valeurs nulles
    - On va tout mettre en minuscule

Colonne "Description"
    - On na va pas retenir cette colonne pour notre analyse métier

Colonne "ProductNameClean"
    - 2512 valeurs nulles   => on va déterminer les valeurs nulles dans un premier temps avec le "stockCode" et dans un second temps avec le "UnitPriceGBP_Propre"

Colonne "UnitPriceGBP_Propre" (Conversion en nombres)
    - Aucune valeur nulle
    - 1 142 valeurs égale à 0  => Pour les valeurs égale à 0, on va estimer la valeur en utiliser la médiane du ratio "UnitPrice / UnitCost" et la valeur de "UnitCost"
    - 660 négatives     => On  va gérer les valeurs négatives avec des valeurs absolues

Colonne "UnitCostGBP_Propre" (conversion en nombre)
    - 812 valeurs nulles        => Pour les valeurs égale à 0, on va estimer la valeur en utiliser la médiane du ratio "UnitPrice / UnitCost" et la valeur de "UnitPrice"
    - 304 valeurs négatives     => Pour les valeurs négatives, on va prendre les valeurs absolues

In [65]:
df_products=duckdb.query(f"""
-- Étape 1 : On crée un tableau virtuel avec tous nos calculs complexes
    SELECT DISTINCT
        StockCode,
        ProductCategory,
        ProductCategoryCode,
        ProductFamily,
        ProductNameClean, 
        REPLACE(UnitPriceGBP, ',', '.')::FLOAT AS UnitPriceGBP_Propre,
        REPLACE(UnitCostGBP, ',', '.')::FLOAT AS UnitCostGBP_Propre   
    FROM read_parquet('{chemin_fichier}')
""").df()

# ---------------------------------

# Création d'une table clients avec :
# ProductCategoryClean : soir la valeur de ProductCategory, soit la valeur de ProductCategoryCode si ProductCategory est null
# ProductFamilyClean : ProductFamily en minuscule
# ProductNameClean_2 : soit la valeur de ProductNameClean, soit la valeur max de ProductNameClean par StockCode si ProductNameClean est null

df_products_clean=duckdb.query(f"""
-- Étape 1 : On gère les conversions de base et les valeurs absolues (ABS)
    WITH Etape1_Nettoyage_Base AS (
        SELECT 
            *,
            -- Conversion en FLOAT et mise en valeur absolue pour régler les 660 et 304 négatifs
            ABS(REPLACE(UnitPriceGBP, ',', '.')::FLOAT) AS Prix_Brut,
            ABS(REPLACE(UnitCostGBP, ',', '.')::FLOAT) AS Cout_Brut,
            
            -- Nettoyage des textes
            TRIM(LOWER(COALESCE(ProductCategory, ProductCategoryCode))) AS ProductCategoryClean,
            TRIM(LOWER(ProductFamily)) as ProductFamilyClean,
            
            -- MODIFICATION ICI : On applique TRIM et LOWER dès le début sur le nom
            TRIM(LOWER(ProductNameClean)) AS Nom_Nettoye
        FROM read_parquet('{chemin_fichier}')
    ),
    
    -- Étape 2 : On calcule la médiane et on fait la 1ère passe sur les noms (par StockCode)
    Etape2_Calculs_Intermediaires AS (
        SELECT 
            *,
            -- Calcul de la médiane du ratio (Prix / Coût)
            MEDIAN(Prix_Brut / NULLIF(Cout_Brut, 0)) OVER () AS Ratio_Mediane,
            
            -- Remplacement des noms vides grâce au StockCode
            COALESCE(
                Nom_Nettoye, 
                MAX(Nom_Nettoye) OVER (PARTITION BY StockCode)
            ) AS Nom_Etape1
        FROM Etape1_Nettoyage_Base
    ),
    
    -- Étape 3 : On applique les formules d'imputation finales
    Etape3_Application_Regles AS (
        SELECT DISTINCT
            StockCode,
            CASE
                WHEN ProductCategoryClean IS NULL THEN 'other'
                ELSE ProductCategoryClean
            END AS ProductCategory_Propre,
            ProductFamilyClean,
            
            -- MODIFICATION ICI : On ajoute 'inconnu' comme ultime solution de secours
            COALESCE(
                Nom_Etape1,
                MAX(Nom_Etape1) OVER (PARTITION BY Prix_Brut),
                'inconnu'
            ) AS ProductNameClean_Final,
            
            -- Imputation du Prix
            CASE 
                WHEN Prix_Brut IS NULL OR Prix_Brut = 0 THEN Cout_Brut * Ratio_Mediane
                ELSE Prix_Brut 
            END AS UnitPriceGBP_Propre,
            
            -- Imputation du Coût
            CASE 
                WHEN Cout_Brut IS NULL OR Cout_Brut = 0 THEN Prix_Brut / NULLIF(Ratio_Mediane, 0)
                ELSE Cout_Brut 
            END AS UnitCostGBP_Propre

        FROM Etape2_Calculs_Intermediaires
    )
    
    -- Résultat final
    SELECT * FROM Etape3_Application_Regles
""").df()

# Requête initiale sans corrections 

# df_clients=duckdb.query(f"""
#     select distinct
#         StockCode,
#         ProductCategoryCode,
#         ProductCategory
#         ProductFamily,
#         ProductNameClean            
#     From read_parquet('{chemin_fichier}')
#     WHERE StockCode='22114'
# """).df()

In [67]:
df_products_clean["StockCode"].value_counts()

StockCode
20713     11
22139     11
21843     11
85099B    11
22423     10
          ..
46775E     1
85086B     1
90200a     1
21763      1
85226B     1
Name: count, Length: 5619, dtype: int64

In [68]:
df_products["StockCode"].value_counts()

StockCode
85099B    21
22356     18
22139     17
20685     17
20725     17
          ..
17129f     1
79161a     1
85226B     1
90160d     1
79030g     1
Name: count, Length: 5619, dtype: int64

In [ ]:
explorer_dataset(df_products_clean)

Start ---------- Pour ce dataset, la taille est de (11027, 6) ----------
------------------------------

,StockCode,ProductCategory_Propre,ProductFamilyClean,ProductNameClean_Final,UnitPriceGBP_Propre,UnitCostGBP_Propre
0,22281,seasonal,occasions,easter tree yellow birds,10.38,4.31
1,23486,home decoration,interior,antique heart shelf unit,10.58,4.13
2,DCGS0067,other,other,ebay,11.06,6.21

------------------------------

,StockCode,ProductCategory_Propre,ProductFamilyClean,ProductNameClean_Final,UnitPriceGBP_Propre,UnitCostGBP_Propre
11024,85226B,other,other,wood stamp set best wishes,2.58,1.19
11025,85064,home decoration,interior,cream sweetheart letter rack,3.32,1.84
11026,22608,other,other,pens assorted funky jeweled,3.47,1.78

------------------------------
Présences de valeurs 'NaN'.
StockCode                 0
ProductCategory_Propre    0
ProductFamilyClean        0
ProductNameClean_Final    0
UnitPriceGBP_Propre       0
UnitCostGBP_Propre        0
dtype: int64

Empty DataFrame
Columns: [StockCode, ProductCategory_Propre, ProductFamilyClean, ProductNameClean_Final, UnitPriceGBP_Propre, UnitCostGBP_Propre]
Index: []

------------------------------
Les doublons
0
------------------------------
Les types de données
StockCode                     str
ProductCategory_Propre        str
ProductFamilyClean            str
ProductNameClean_Final        str
UnitPriceGBP_Propre       float32
UnitCostGBP_Propre        float32
dtype: object
------------------------------
Description

,count,mean,std,min,25%,50%,75%,max
UnitPriceGBP_Propre,11027.0,10.930378,7.355229,0.327969,5.445,9.50,14.08,44.788315
UnitCostGBP_Propre,11027.0,5.363453,3.766693,0.160000,2.550,4.55,7.07,23.180000

FIN----------------------------------------------------------------------------------------------------

Pour la table de faits, on va garder :

La colonne "OrderLineID"
    - Aucune valeur nulle

La colonne "Invoice"
    - Aucune valeur nulle

La colonne "Quantity":
    - Aucune valeure nulle
    - Mais des valeurs avec du texte : on va juste retirer les "units"
    - Des valeurs "négatifs" => On va considérer que ce sont des retours

La colonne "CustomerID"
    - 4416 valeurs nulles => On va les remplacer par 0 pour rester en format integer

La colonne "Country"
    - Aucune valeur nulle mais on va devoir corriger certaines valeurs de texte pour homogénéiser les noms de pays

La colonne "StockCode"
    - Aucune valeure nulle
    - On va rester en format texte

La colonne  "Promotion Code"
    - 45 valeurs nulles

In [104]:
df_order=duckdb.query(f"""
    SELECT DISTINCT
        OrderLineID,
        Invoice,
        TRIM(REPLACE(Quantity, 'units', ''))::integer as Quantity_clean,              
        CASE
            WHEN CustomerID IS NULL THEN '0'
            ELSE CustomerID
        END AS CustomerID_clean,
        Country,
        StockCode,           
        PromotionCode      
    FROM read_parquet('{chemin_fichier}')
""").df()


# On prend plutôt la colonne StockCode plutôt que ProductNameClean pour identifier les produits
# On enlève le DeliveryTime qui apporte peu d'informations
# On enlève le warehouseID qui est un identifiant de l'entrepôt et qui n'apporte pas d'informations sur le produit

df_order_clean=duckdb.query(f"""
-- Étape 1 : On nettoie les virgules et on convertit en nombres
    WITH Etape1_Nettoyage AS (
        SELECT DISTINCT
            OrderLineID,
            Invoice,
            Quantity,
            CustomerID,
            Country,
            REPLACE(UnitPriceGBP, ',', '.')::FLOAT AS UnitPriceGBP_Propre,
            REPLACE(UnitCostGBP, ',', '.')::FLOAT AS UnitCostGBP_Propre,
            StockCode,
            PromotionCode            
        FROM read_parquet('{chemin_fichier}')
    ),
    
    -- Étape 2 : On calcule la médiane du Markup sur toute la base
    Etape2_Mediane AS (
        SELECT 
            *,
            -- NULLIF(..., 0) est une sécurité pour ne jamais diviser par zéro
            UnitPriceGBP_Propre / NULLIF(UnitCostGBP_Propre, 0) AS Markup_Initial,
            
            -- MEDIAN() OVER() calcule la médiane globale pour pouvoir l'utiliser partout
            MEDIAN(UnitPriceGBP_Propre / NULLIF(UnitCostGBP_Propre, 0)) OVER () AS Mediane_Markup
        FROM Etape1_Nettoyage
    )
    
    -- Étape 3 : On applique votre règle de remplacement
    SELECT 
        OrderLineID,
        Invoice,
        Quantity,
        CustomerID,
        Country,
        UnitPriceGBP_Propre,
        
        -- Si le coût est vide, on prend (Prix / Mediane)
        COALESCE(UnitCostGBP_Propre, UnitPriceGBP_Propre / Mediane_Markup) AS UnitCostGBP_Propre,
        
        -- Le Markup final sera donc soit le vrai, soit la médiane
        COALESCE(Markup_Initial, Mediane_Markup) AS Markup,
        
        StockCode,
        PromotionCode
    FROM Etape2_Mediane
""").df()

In [105]:
df_order.head(20)

,OrderLineID,Invoice,Quantity_clean,CustomerID_clean,Country,StockCode,PromotionCode
0,978546,575477,1,0,United Kingdom,22683,SPRING
1,978554,575477,1,0,United Kingdom,22703,SPRING
2,978579,575477,13,0,United Kingdom,22815,SPRING
3,978587,575477,1,0,United Kingdom,22867,SPRING
4,978616,575477,1,0,United Kingdom,22995,SPRING
5,978627,575477,3,0,United Kingdom,23089,SPRING
6,978633,575477,1,0,United Kingdom,23119,SPRING
7,978643,575477,1,0,United Kingdom,23188,SPRING
8,978663,575477,1,0,United Kingdom,23242,SPRING
9,978687,575477,2,0,United Kingdom,23318,SPRING
10,978708,575477,2,0,United Kingdom,23399,SPRING
11,978766,575477,4,0,United Kingdom,72817,SPRING
12,978775,575477,1,0,United Kingdom,82583,SPRING
13,978821,575477,1,0,United Kingdom,90195A,SPRING
14,978826,575477,1,0,United Kingdom,15034,SPRING
15,978831,575477,2,0,United Kingdom,17084P,SPRING
16,978859,575481,4,15679.0,United Kingdom,22621,NONE
17,978872,575481,4,15679.0,United Kingdom,22620,NONE
18,978963,575482,1,15916.0,United Kingdom,22423,NONE
19,978969,575482,1,0,United Kingdom,22119,NONE

In [106]:
explorer_dataset(df_order)

Start ---------- Pour ce dataset, la taille est de (1067371, 7) ----------
------------------------------

,OrderLineID,Invoice,Quantity_clean,CustomerID_clean,Country,StockCode,PromotionCode
0,978546,575477,1,0,United Kingdom,22683,SPRING
1,978554,575477,1,0,United Kingdom,22703,SPRING
2,978579,575477,13,0,United Kingdom,22815,SPRING

------------------------------

,OrderLineID,Invoice,Quantity_clean,CustomerID_clean,Country,StockCode,PromotionCode
1067368,733664,555106,24,12790.0,Netherlands,22540,WELCOME10
1067369,733720,555108,1,18231.0,United Kingdom,21770,XMAS
1067370,733734,555108,1,18231.0,United Kingdom,22055,XMAS

------------------------------
Présences de valeurs 'NaN'.
OrderLineID            0
Invoice                0
Quantity_clean         0
CustomerID_clean       0
Country                0
StockCode              0
PromotionCode       1764
dtype: int64

,OrderLineID,Invoice,Quantity_clean,CustomerID_clean,Country,StockCode,PromotionCode
1166,1016252,578065,2,0,United Kingdom,22812,NaN
1656,1032141,579149,6,13844.0,United Kingdom,22734,NaN
2203,1049485,580527,2,13736.0,United Kingdom,82600,NaN
2301,1052305,580677,1,16200.0,United Kingdom,48184,NaN
3930,526841,536539,4,15165.0,United Kingdom,37495,NaN
...,...,...,...,...,...,...,...
1063837,620906,544457,10,14667.0,United Kingdom,22663,NaN
1065064,658548,547722,12,12553.0,France,21086,NaN
1065897,685249,550360,2,14978.0,United Kingdom,22835,NaN
1066992,721204,553739,24,14895.0,United Kingdom,22630,NaN
1067222,728649,554512,1,0,United Kingdom,22766,NaN

------------------------------
Les doublons
0
------------------------------
Les types de données
OrderLineID           str
Invoice               str
Quantity_clean      int32
CustomerID_clean      str
Country               str
StockCode             str
PromotionCode         str
dtype: object
------------------------------
Description

,count,mean,std,min,25%,50%,75%,max
Quantity_clean,1067371.0,71.011551,2476.529466,-80995.0,1.0,3.0,10.0,99999.0

FIN----------------------------------------------------------------------------------------------------