In [1]:
from numpy import select
import pandas as pd
import duckdb
pd.set_option('display.max_columns', None)

chemin_fichier = r"retailcorps.parquet"

df=duckdb.query(f"""
    select distinct *
    From read_parquet('{chemin_fichier}')
""").df()

In [2]:
def explorer_dataset(dataset):
        print(f"Start {'-'*10} Pour ce dataset, la taille est de {dataset.shape} {'-'*10}")
        print('-'*30)
        display(dataset.head(3))
        print('-'*30)
        display(dataset.tail(3))
        print('-'*30)
        print(f"Présences de valeurs 'NaN'.")
        print(f"{dataset.isna().sum()}")
        display(dataset[dataset.isna().any(axis=1)])
        print('-'*30)
        print(f"Les doublons")
        print(f"{dataset.duplicated().sum()}")
        print('-'*30)
        print(f"Les types de données")
        print(f"{dataset.dtypes}")
        print('-'*30)
        print(f"Description")
        display(dataset.describe().T)
        print("FIN"+'-'*100)

In [ ]:
explorer_dataset(df)

Start ---------- Pour ce dataset, la taille est de (1067371, 27) ----------
------------------------------

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,ProductFamily,ProductNameClean,UnitPriceGBP,UnitCostGBP,CustomerSegment,CustomerType,LoyaltyProgram,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
0,611407,543530,90214A,"LETTER ""A"" BLING KEY RING",1,2011-02-09 12:46:00,NaN,United Kingdom,OTHER,Other,Other,"Letter ""A"" Bling Key Ring",12.13,7.69,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,SPRING,0.05,Completed,2,Europe,Western Europe,GBP
1,611447,543532,22467,GUMBALL COAT RACK,1,2011-02-09 12:59:00,NaN,United Kingdom,OTHER,Other,Other,Gumball Coat Rack,14.8,8.35,VIP,Retailer,Gold,Phone,Invoice,WH-UK-02,NONE,0.0,Completed,7,Europe,Western Europe,GBP
2,611589,543535,22667,RECIPE BOX RETROSPOT,6,2011-02-09 13:37:00,17537.0,United Kingdom,OTHER,Other,Other,Recipe Box Retrospot,4.14,2.21,Loyal,Small business,Silver,Store,Bank transfer,WH-UK-01,SPRING,0.05,Completed,4,Europe,Western Europe,GBP

------------------------------

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,ProductFamily,ProductNameClean,UnitPriceGBP,UnitCostGBP,CustomerSegment,CustomerType,LoyaltyProgram,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
1067368,122195,501080,21865,PINK UNION JACK PASSPORT COVER,1,2010-03-12 11:19:00,NaN,United Kingdom,OTHER,Other,Other,Pink Union Jack Passport Cover,6.96,2.7,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP
1067369,122254,501080,22348,TEA BAG PLATE RED SPOTTY,2,2010-03-12 11:19:00,NaN,United Kingdom,KITCHEN,Kitchenware,Interior,Tea Bag Plate Red Spotty,9.65,5.67,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP
1067370,122284,501080,35004C,SET OF 3 COLOURED FLYING DUCKS,1,2010-03-12 11:19:00,NaN,United Kingdom,OTHER,Other,Other,Set Of 3 Coloured Flying Ducks,14.62,8.13,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP

------------------------------
Présences de valeurs 'NaN'.
OrderLineID                 0
Invoice                     0
StockCode                   0
Description             12934
Quantity                    0
InvoiceDate                 0
CustomerID             252975
Country                     0
ProductCategoryCode      3210
ProductCategory          4324
ProductFamily               0
ProductNameClean         4382
UnitPriceGBP                0
UnitCostGBP              1039
CustomerSegment             0
CustomerType                0
LoyaltyProgram              0
SalesChannel             4178
PaymentMethod               0
WarehouseID              1767
PromotionCode            1764
DiscountRate              635
OrderStatus              1327
DeliveryTime              806
Continent                   0
Region                      0
Currency                 1666
dtype: int64

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,ProductFamily,ProductNameClean,UnitPriceGBP,UnitCostGBP,CustomerSegment,CustomerType,LoyaltyProgram,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
0,611407,543530,90214A,"LETTER ""A"" BLING KEY RING",1,2011-02-09 12:46:00,NaN,United Kingdom,OTHER,Other,Other,"Letter ""A"" Bling Key Ring",12.13,7.69,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,SPRING,0.05,Completed,2,Europe,Western Europe,GBP
1,611447,543532,22467,GUMBALL COAT RACK,1,2011-02-09 12:59:00,NaN,United Kingdom,OTHER,Other,Other,Gumball Coat Rack,14.8,8.35,VIP,Retailer,Gold,Phone,Invoice,WH-UK-02,NONE,0.0,Completed,7,Europe,Western Europe,GBP
3,611817,543546,21294,ETCHED GLASS COASTER,6,2011-02-09 16:52:00,NaN,United Kingdom,OTHER,Other,Other,Etched Glass Coaster,9.86,3.5,VIP,Retailer,Gold,Online,Card,WH-UK-01,NONE,0.0,Completed,8,Europe,Western Europe,GBP
4,611913,543546,84279B,CHERRY BLOSSOM DECORATIVE FLASK,1,2011-02-09 16:52:00,NaN,United Kingdom,OTHER,Other,Other,Cherry Blossom Decorative Flask,12.66,7.15,VIP,Retailer,Gold,Online,Card,WH-UK-01,NONE,0.0,Completed,8,Europe,Western Europe,GBP
13,612470,543629,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2011-02-10 15:55:00,NaN,United Kingdom,KITCHEN,Kitchenware,Interior,Set 2 Tea Towels I Love London,22.88,11.03,VIP,Retailer,Gold,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,7,Europe,Western Europe,GBP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1067366,122177,501080,21578,WOODLAND DESIGN COTTON TOTE BAG,1,2010-03-12 11:19:00,NaN,United Kingdom,HOME,Home decoration,Interior,Woodland Design Cotton Tote Bag,21.76,10.46,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP
1067367,122193,501080,21846,PINK DIAMANTE PEN IN GIFT BOX,1,2010-03-12 11:19:00,NaN,United Kingdom,GIFT,Gifts,Occasions,Pink Diamante Pen In Gift Box,7.89,"2,86",VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP
1067368,122195,501080,21865,PINK UNION JACK PASSPORT COVER,1,2010-03-12 11:19:00,NaN,United Kingdom,OTHER,Other,Other,Pink Union Jack Passport Cover,6.96,2.7,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP
1067369,122254,501080,22348,TEA BAG PLATE RED SPOTTY,2,2010-03-12 11:19:00,NaN,United Kingdom,KITCHEN,Kitchenware,Interior,Tea Bag Plate Red Spotty,9.65,5.67,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP
1067370,122284,501080,35004C,SET OF 3 COLOURED FLYING DUCKS,1,2010-03-12 11:19:00,NaN,United Kingdom,OTHER,Other,Other,Set Of 3 Coloured Flying Ducks,14.62,8.13,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,12,Europe,Western Europe,GBP

------------------------------
Les doublons
0
------------------------------
Les types de données
OrderLineID            str
Invoice                str
StockCode              str
Description            str
Quantity               str
InvoiceDate            str
CustomerID             str
Country                str
ProductCategoryCode    str
ProductCategory        str
ProductFamily          str
ProductNameClean       str
UnitPriceGBP           str
UnitCostGBP            str
CustomerSegment        str
CustomerType           str
LoyaltyProgram         str
SalesChannel           str
PaymentMethod          str
WarehouseID            str
PromotionCode          str
DiscountRate           str
OrderStatus            str
DeliveryTime           str
Continent              str
Region                 str
Currency               str
dtype: object
------------------------------
Description

,count,unique,top,freq
OrderLineID,1067371,1067371,611407,1
Invoice,1067371,53628,537434,1350
StockCode,1067371,5619,85123A,5776
Description,1054437,9081,WHITE HANGING HEART T-LIGHT HOLDER,5776
Quantity,1067371,1150,1,292698
InvoiceDate,1067371,55180,2010-12-06 16:57:00,1332
CustomerID,814396,5942,17841.0,12947
Country,1067371,61,United Kingdom,969892
ProductCategoryCode,1064161,7,OTHER,451026
ProductCategory,1063047,14,Other,448331
ProductFamily,1067371,4,Other,452379
ProductNameClean,1062989,5620,White Hanging Heart T-Light Holder,5918
UnitPriceGBP,1067371,4348,14.47,6039
UnitCostGBP,1066332,2611,7.81,7618
CustomerSegment,1067371,4,VIP,447028
CustomerType,1067371,3,Retailer,529270
LoyaltyProgram,1067371,4,Gold,447028
SalesChannel,1063193,4,Marketplace,270563
PaymentMethod,1067371,4,PayPal,271614
WarehouseID,1065604,9,WH-UK-01,492799
PromotionCode,1065607,5,SPRING,221792
DiscountRate,1066736,6,0.05,221802
OrderStatus,1066044,3,Completed,937812
DeliveryTime,1066565,19,15,75869
Continent,1067371,6,Europe,1062492
Region,1067371,11,Western Europe,1049690
Currency,1065705,15,GBP,983751

FIN----------------------------------------------------------------------------------------------------

Dans la table df_product (18 284 lignes) :

Colonne "StockCode"
    - Aucune valeure nulle

Colonne "ProductCategory"
    - 2017 valeurs nulles

Colonne "ProductCategoryCode"
    - 1762 valeurs nulles
=> Les colonnes "ProductCategory" et "ProductCategoryCode" sont redondants : On va créer une colonne ProductCategory_Clean qui sera une combinaison des deux

Colonne "ProductFamily"
    - Aucune valeurs nulles
    - On va tout mettre en minuscule

Colonne "Description"
    - On na va pas retenir cette colonne pour notre analyse métier

Colonne "ProductNameClean"
    - 2512 valeurs nulles   => on va déterminer les valeurs nulles dans un premier temps avec le "stockCode" et dans un second temps avec le "UnitPriceGBP_Propre"

Colonne "UnitPriceGBP_Propre" (Conversion en nombres)
    - Aucune valeur nulle
    - 1 142 valeurs égale à 0  => Pour les valeurs égale à 0, on va estimer la valeur en utiliser la médiane du ratio "UnitPrice / UnitCost" et la valeur de "UnitCost"
    - 660 négatives     => On  va gérer les valeurs négatives avec des valeurs absolues

Colonne "UnitCostGBP_Propre" (conversion en nombre)
    - 812 valeurs nulles        => Pour les valeurs égale à 0, on va estimer la valeur en utiliser la médiane du ratio "UnitPrice / UnitCost" et la valeur de "UnitPrice"
    - 304 valeurs négatives     => Pour les valeurs négatives, on va prendre les valeurs absolues

In [197]:
df_products=duckdb.query(f"""
-- Étape 1 : On crée un tableau virtuel avec tous nos calculs complexes
    SELECT DISTINCT
        StockCode,
        ProductCategory,
        ProductCategoryCode,
        ProductFamily,
        ProductNameClean, 
        REPLACE(UnitPriceGBP, ',', '.')::FLOAT AS UnitPriceGBP_Propre,
        REPLACE(UnitCostGBP, ',', '.')::FLOAT AS UnitCostGBP_Propre   
    FROM read_parquet('{chemin_fichier}')
""").df()

# ---------------------------------

# Création d'une table clients avec :
# ProductCategoryClean : soir la valeur de ProductCategory, soit la valeur de ProductCategoryCode si ProductCategory est null
# ProductFamilyClean : ProductFamily en minuscule
# ProductNameClean_2 : soit la valeur de ProductNameClean, soit la valeur max de ProductNameClean par StockCode si ProductNameClean est null

df_products_clean=duckdb.query(f"""
-- Étape 1 : On gère les conversions de base et les valeurs absolues (ABS)
    WITH Etape1_Nettoyage_Base AS (
        SELECT 
            TRIM(UPPER(StockCode)) AS StockCode,
            ABS(REPLACE(UnitPriceGBP, ',', '.')::FLOAT) AS Prix_Brut,
            ABS(REPLACE(UnitCostGBP, ',', '.')::FLOAT) AS Cout_Brut,
            TRIM(LOWER(COALESCE(ProductCategory, ProductCategoryCode))) AS ProductCategoryClean,
            TRIM(LOWER(ProductFamily)) as ProductFamilyClean,
            TRIM(LOWER(ProductNameClean)) AS Nom_Nettoye
        FROM read_parquet('{chemin_fichier}')
    ),
    
    -- Étape 2 : On calcule la médiane et on fait la 1ère passe sur les noms (par StockCode)
    Etape2_Calculs_Intermediaires AS (
        SELECT 
            *,
            MEDIAN(Prix_Brut / NULLIF(Cout_Brut, 0)) OVER () AS Ratio_Mediane,
            COALESCE(
                Nom_Nettoye, 
                MAX(Nom_Nettoye) OVER (PARTITION BY StockCode)
            ) AS Nom_Etape1
        FROM Etape1_Nettoyage_Base
    ),
    
    -- Étape 3 : On applique les formules d'imputation
    Etape3_Application_Regles AS (
        SELECT 
            StockCode,
            CASE
                WHEN ProductCategoryClean IS NULL THEN 'other'
                ELSE ProductCategoryClean
            END AS ProductCategory_Propre,
            ProductFamilyClean,
            COALESCE(
                Nom_Etape1,
                MAX(Nom_Etape1) OVER (PARTITION BY Prix_Brut),
                'inconnu'
            ) AS ProductNameClean_Final,
            CASE 
                WHEN Prix_Brut IS NULL OR Prix_Brut = 0 THEN Cout_Brut * Ratio_Mediane
                ELSE Prix_Brut 
            END AS UnitPriceGBP_Propre,
            CASE 
                WHEN Cout_Brut IS NULL OR Cout_Brut = 0 THEN Prix_Brut / NULLIF(Ratio_Mediane, 0)
                ELSE Cout_Brut 
            END AS UnitCostGBP_Propre
        FROM Etape2_Calculs_Intermediaires
    ),
    
    -- Étape 4 : Déduplication (On garde une seule ligne par StockCode avec la valeur la plus fréquente)
    Etape4_Deduplication AS (
        SELECT 
            StockCode,
            MODE(ProductCategory_Propre) AS ProductCategory_Propre,
            MODE(ProductFamilyClean) AS ProductFamilyClean,
            MODE(ProductNameClean_Final) AS ProductNameClean_Final,
            MODE(UnitPriceGBP_Propre) AS UnitPriceGBP_Propre,
            MODE(UnitCostGBP_Propre) AS UnitCostGBP_Propre
        FROM Etape3_Application_Regles
        GROUP BY StockCode
    )
    
    -- Résultat final
    SELECT * FROM Etape4_Deduplication
""").df()

# Requête initiale sans corrections 

# df_clients=duckdb.query(f"""
#     select distinct
#         StockCode,
#         ProductCategoryCode,
#         ProductCategory
#         ProductFamily,
#         ProductNameClean            
#     From read_parquet('{chemin_fichier}')
#     WHERE StockCode='22114'
# """).df()

In [195]:
df_products_clean[df_products_clean['StockCode'].str.upper() == '47503J']['StockCode'].apply(len)

65    6
Name: StockCode, dtype: int64

In [196]:
df_products_clean[df_products_clean['StockCode'].str.contains('47503', case=False, na=False)]

,StockCode,ProductCategory_Propre,ProductFamilyClean,ProductNameClean_Final,UnitPriceGBP_Propre,UnitCostGBP_Propre
65,47503J,gifts,occasions,set/3 floral garden tools in bag,9.70,5.62
1198,47503J,gifts,occasions,set/3 floral garden tools in bag,17.33,6.03
3352,47503G,stationery,office,ass floral print tape measure,4.15,1.36
3386,47503K,other,other,assorted floral secateurs,11.07,5.25
4291,47503A,other,other,ass floral print multi screwdriver,10.63,4.40
4645,47503E,other,other,ass floral print scissors,5.34,2.64
4776,47503H,other,other,ass floral print spirit level,3.00,1.26
4804,47503F,other,other,ass floral print torch,14.11,5.73

In [198]:
duckdb.query("""
COPY (
    SELECT * FROM df_products_clean
)
TO 'D_products.parquet'
(FORMAT PARQUET)
""")

In [194]:
df_products_clean['StockCode'].value_counts()

StockCode
84798A    1
90140     1
90099     1
37333     1
23015     1
         ..
23067     1
37490C    1
90129E    1
85168A    1
90127B    1
Name: count, Length: 5132, dtype: int64

In [186]:
explorer_dataset(df_products_clean)

Start ---------- Pour ce dataset, la taille est de (5132, 6) ----------
------------------------------

,StockCode,ProductCategory_Propre,ProductFamilyClean,ProductNameClean_Final,UnitPriceGBP_Propre,UnitCostGBP_Propre
0,84798A,other,other,pink foxglove artiifcial flower,3.61,2.15
1,90140,other,other,pink sweetie necklace,3.61,1.89
2,90099,other,other,necklace+bracelet set blue hibiscus,13.40,8.41

------------------------------

,StockCode,ProductCategory_Propre,ProductFamilyClean,ProductNameClean_Final,UnitPriceGBP_Propre,UnitCostGBP_Propre
5129,90129E,gifts,occasions,purple glass tassle bag charm,14.36,7.47
5130,85168A,other,other,white baroque carriage clock,2.49,1.27
5131,90127B,other,other,blue beads+hand phone charm,2.50,1.00

------------------------------
Présences de valeurs 'NaN'.
StockCode                 0
ProductCategory_Propre    0
ProductFamilyClean        0
ProductNameClean_Final    0
UnitPriceGBP_Propre       0
UnitCostGBP_Propre        0
dtype: int64

Empty DataFrame
Columns: [StockCode, ProductCategory_Propre, ProductFamilyClean, ProductNameClean_Final, UnitPriceGBP_Propre, UnitCostGBP_Propre]
Index: []

------------------------------
Les doublons
0
------------------------------
Les types de données
StockCode                     str
ProductCategory_Propre        str
ProductFamilyClean            str
ProductNameClean_Final        str
UnitPriceGBP_Propre       float32
UnitCostGBP_Propre        float32
dtype: object
------------------------------
Description

,count,mean,std,min,25%,50%,75%,max
UnitPriceGBP_Propre,5132.0,10.802623,7.277306,0.55,5.40,9.39,13.9225,39.900002
UnitCostGBP_Propre,5132.0,5.268578,3.724627,0.16,2.46,4.47,6.9800,23.180000

FIN----------------------------------------------------------------------------------------------------

Pour la table de faits, on va garder :

La colonne "OrderLineID"
    - Aucune valeur nulle

La colonne "Invoice"
    - Aucune valeur nulle

La colonne "Quantity":
    - Aucune valeure nulle
    - Mais des valeurs avec du texte : on va juste retirer les "units"
    - Des valeurs "négatifs" => On va considérer que ce sont des retours
    - Il y a 632 lignes de commandes avec la valeur "99999" => on va les remplacer par la médiane arrondie

La colonne "CustomerID"
    - 4416 valeurs nulles => On va les remplacer par 0 pour rester en format integer

La colonne "Country"
    - Aucune valeur nulle mais on va devoir corriger certaines valeurs de texte pour homogénéiser les noms de pays

La colonne "StockCode"
    - Aucune valeure nulle
    - On va rester en format texte

La colonne  "Promotion Code"
    - 45 valeurs nulles

In [199]:
df_order_clean=duckdb.query(f"""
-- Étape 1 : On nettoie avec vos règles exactes
    WITH Etape1_Nettoyage AS (
        SELECT DISTINCT
            OrderLineID,
            TRIM(LOWER(OrderStatus)) AS OrderStatus,
            Invoice,         
            CASE
                WHEN CustomerID IS NULL THEN '0'
                ELSE CustomerID
            END AS CustomerID_clean,
            
            -- Homogénéisation des noms de pays
            CASE
                WHEN UPPER(TRIM(Country)) IN ('UNITED KINGDOM', 'UK', 'U.K.', 'GREAT BRITAIN') THEN 'United Kingdom'
                WHEN UPPER(TRIM(Country)) IN ('GERMANY', 'DEUTSCHLAND', 'DE')                  THEN 'Germany'
                WHEN UPPER(TRIM(Country)) IN ('FRANCE', 'FR')                                  THEN 'France'
                WHEN UPPER(TRIM(Country)) IN ('EIRE', 'REPUBLIC OF IRELAND')                   THEN 'Ireland'
                WHEN UPPER(TRIM(Country)) IN ('NETHERLANDS', 'HOLLAND', 'NL')                  THEN 'Netherlands'
                WHEN UPPER(TRIM(Country)) IN ('SWITZERLAND', 'CH')                             THEN 'Switzerland'
                WHEN UPPER(TRIM(Country)) IN ('AUSTRALIA', 'AUS')                              THEN 'Australia'
                WHEN UPPER(TRIM(Country)) IN ('USA', 'UNITED STATES')                          THEN 'United States'
                WHEN UPPER(TRIM(Country)) = 'UNITED ARAB EMIRATES'                             THEN 'United Arab Emirates'
                WHEN UPPER(TRIM(Country)) = 'SOUTH AFRICA'                                     THEN 'South Africa'
                ELSE UPPER(SUBSTRING(TRIM(Country), 1, 1)) || LOWER(SUBSTRING(TRIM(Country), 2))
            END AS Country_clean,
            
            TRIM(UPPER(StockCode)) AS StockCode,
            ABS(TRIM(REPLACE(Quantity, 'units', ''))::integer) as Quantity_clean,
            
            -- NOUVEAU : Déduction du PromotionCode grâce au DiscountRate
            CASE 
                WHEN TRY_CAST(DiscountRate AS FLOAT) = 0.05 THEN 'SPRING'
                WHEN TRY_CAST(DiscountRate AS FLOAT) = 0.10 THEN 'WELCOME10'
                WHEN TRY_CAST(DiscountRate AS FLOAT) = 0.15 THEN 'XMAS'
                WHEN TRY_CAST(DiscountRate AS FLOAT) = 0.20 THEN 'CLEARANCE'
                WHEN TRY_CAST(DiscountRate AS FLOAT) = 0.30 THEN 'VIP'
                WHEN TRY_CAST(DiscountRate AS FLOAT) = 0.00 THEN 'NONE'
                
                -- Si DiscountRate vaut 'None' ou est vide (TRY_CAST échoue), on garde le PromotionCode d'origine nettoyé
                ELSE UPPER(TRIM(COALESCE(PromotionCode, 'NONE')))
            END AS PromotionCode_clean
            
        FROM read_parquet('{chemin_fichier}')
    ),
    
    -- Étape 2 : Calcul des statistiques (Moyenne, Écart-Type, Médiane)
    Etape2_Stats AS (
        SELECT 
            *,
            -- 1. Calcul de la moyenne globale
            AVG(Quantity_clean) OVER () AS Moyenne_Globale,
            
            -- 2. Calcul de l'écart-type global
            STDDEV(Quantity_clean) OVER () AS Ecart_Type_Global,
            
            -- 3. Calcul de la médiane par produit (pour le remplacement)
            ROUND(MEDIAN(Quantity_clean) OVER (PARTITION BY StockCode), 0)::INTEGER AS Mediane_Quantite_Produit,
            
            -- 4. Médiane globale de secours (si le produit n'a pas d'historique valide)
            ROUND(MEDIAN(Quantity_clean) OVER (), 0)::INTEGER AS Mediane_Quantite_Globale
            
        FROM Etape1_Nettoyage
    )
    
    -- Étape 3 : On applique la règle des "3 Sigmas" sur la quantité
    SELECT 
        OrderLineID,
        CASE
            WHEN OrderStatus IS NULL THEN 'completed'
            ELSE OrderStatus
        END AS OrderStatus,
        Invoice,
        CustomerID_clean,
        Country_clean,
        StockCode,
        
        -- Si Quantité > Moyenne + (3 * Ecart-Type), on remplace par la médiane
        CASE 
            WHEN Quantity_clean > (Moyenne_Globale + (3 * Ecart_Type_Global)) 
                 THEN COALESCE(Mediane_Quantite_Produit, Mediane_Quantite_Globale)
            ELSE Quantity_clean
        END AS Quantity_clean,
        
        -- On affiche uniquement notre code promo final ultra-propre !
        PromotionCode_clean
        
    FROM Etape2_Stats
""").df()

In [189]:
df_order_clean.head(10)

,OrderLineID,OrderStatus,Invoice,CustomerID_clean,Country_clean,StockCode,Quantity_clean,PromotionCode_clean
0,695851,cancelled,551291,14298.0,United Kingdom,21028,20,CLEARANCE
1,996057,returned,576618,0,United Kingdom,21028,1,CLEARANCE
2,592326,completed,541827,0,United Kingdom,21028,11,SPRING
3,570717,completed,540255,0,United Kingdom,21028,1,CLEARANCE
4,577994,completed,540798,17365.0,United Kingdom,21028,3,NONE
5,580414,completed,540977,0,United Kingdom,21028,3,WELCOME10
6,15535,completed,490693,14670.0,United Kingdom,21028,1,WELCOME10
7,984746,completed,575875,0,United Kingdom,21028,1,NONE
8,1007221,completed,577358,0,United Kingdom,21028,1,SPRING
9,39531,completed,492729,15911.0,United Kingdom,21028,1,CLEARANCE

In [174]:
explorer_dataset(df_order_clean)

Start ---------- Pour ce dataset, la taille est de (1067371, 8) ----------
------------------------------

,OrderLineID,OrderStatus,Invoice,CustomerID_clean,Country_clean,StockCode,Quantity_clean,PromotionCode_clean
0,67704,completed,495383,17141.0,United Kingdom,21626,3,SPRING
1,277679,completed,516378,14855.0,United Kingdom,21626,12,WELCOME10
2,10745,completed,490279,16891.0,United Kingdom,21626,1,XMAS

------------------------------

,OrderLineID,OrderStatus,Invoice,CustomerID_clean,Country_clean,StockCode,Quantity_clean,PromotionCode_clean
1067368,285415,completed,517120,15142.0,United Kingdom,22589,6,WELCOME10
1067369,892578,cancelled,568868,12957.0,United Kingdom,22589,6,CLEARANCE
1067370,985575,completed,575895,17052.0,United Kingdom,22589,7,NONE

------------------------------
Présences de valeurs 'NaN'.
OrderLineID            0
OrderStatus            0
Invoice                0
CustomerID_clean       0
Country_clean          0
StockCode              0
Quantity_clean         0
PromotionCode_clean    0
dtype: int64

Empty DataFrame
Columns: [OrderLineID, OrderStatus, Invoice, CustomerID_clean, Country_clean, StockCode, Quantity_clean, PromotionCode_clean]
Index: []

------------------------------
Les doublons
0
------------------------------
Les types de données
OrderLineID              str
OrderStatus              str
Invoice                  str
CustomerID_clean         str
Country_clean            str
StockCode                str
Quantity_clean         int32
PromotionCode_clean      str
dtype: object
------------------------------
Description

                    count       mean         std  min  25%  50%   75%      max
Quantity_clean  1067371.0  11.726951  188.302963  1.0  1.0  3.0  10.0  99999.0

FIN----------------------------------------------------------------------------------------------------

In [ ]:
df_order_clean['OrderStatus'].value_counts()

OrderStatus
completed    937812
cancelled     65022
returned      63210
Name: count, dtype: int64

In [190]:
df_order_final = duckdb.query(f"""
    SELECT 
        -- 1. On sélectionne toutes les colonnes de notre table principale (Commandes)
        o.*,
        
        -- 2. On sélectionne UNIQUEMENT les colonnes voulues de la table secondaire (Produits)
        p.ProductNameClean_Final,
        p.ProductFamilyClean,
        o.Quantity_clean * p.UnitPriceGBP_Propre AS TotalPriceGBP,
    -- On définit nos tables et on leur donne des "surnoms" (alias) pour alléger le code
    FROM df_order_clean AS o
    
    -- 3. La clé de voûte : on relie les deux tables grâce au StockCode
    LEFT JOIN df_products_clean AS p
        ON o.StockCode = p.StockCode
""").df()

display(df_order_final.head())

,OrderLineID,OrderStatus,Invoice,CustomerID_clean,Country_clean,StockCode,Quantity_clean,PromotionCode_clean,ProductNameClean_Final,ProductFamilyClean,TotalPriceGBP
0,379405,completed,525950,16539.0,United Kingdom,21955,10,SPRING,doormat union jack guns and roses,other,115.50
1,45114,completed,493404,0,United Kingdom,21955,1,XMAS,doormat union jack guns and roses,other,11.55
2,394192,completed,527268,13059.0,United Kingdom,21955,1,NONE,doormat union jack guns and roses,other,11.55
3,348067,completed,523291,14534.0,United Kingdom,21955,10,NONE,doormat union jack guns and roses,other,115.50
4,605381,completed,543013,0,United Kingdom,21955,1,CLEARANCE,doormat union jack guns and roses,other,11.55

In [176]:
explorer_dataset(df_order_final)

Start ---------- Pour ce dataset, la taille est de (1067371, 11) ----------
------------------------------

,OrderLineID,OrderStatus,Invoice,CustomerID_clean,Country_clean,StockCode,Quantity_clean,PromotionCode_clean,ProductNameClean_Final,ProductFamilyClean,TotalPriceGBP
0,1052461,completed,580688,15550.0,United Kingdom,22178,6,CLEARANCE,victorian glass hanging t-light,interior,29.400002
1,723576,completed,554013,13308.0,United Kingdom,22178,12,SPRING,victorian glass hanging t-light,interior,58.800003
2,673774,completed,C549230,12949.0,United Kingdom,22178,12,NONE,victorian glass hanging t-light,interior,58.800003

------------------------------

,OrderLineID,OrderStatus,Invoice,CustomerID_clean,Country_clean,StockCode,Quantity_clean,PromotionCode_clean,ProductNameClean_Final,ProductFamilyClean,TotalPriceGBP
1067368,998874,completed,576833,17434.0,United Kingdom,20992,24,NONE,jazz hearts purse notebook,office,126.00
1067369,949474,completed,573176,0,United Kingdom,20992,1,CLEARANCE,jazz hearts purse notebook,office,5.25
1067370,983881,completed,575837,12748.0,United Kingdom,20992,10,SPRING,jazz hearts purse notebook,office,52.50

------------------------------
Présences de valeurs 'NaN'.
OrderLineID               0
OrderStatus               0
Invoice                   0
CustomerID_clean          0
Country_clean             0
StockCode                 0
Quantity_clean            0
PromotionCode_clean       0
ProductNameClean_Final    0
ProductFamilyClean        0
TotalPriceGBP             0
dtype: int64

Empty DataFrame
Columns: [OrderLineID, OrderStatus, Invoice, CustomerID_clean, Country_clean, StockCode, Quantity_clean, PromotionCode_clean, ProductNameClean_Final, ProductFamilyClean, TotalPriceGBP]
Index: []

------------------------------
Les doublons
0
------------------------------
Les types de données
OrderLineID                   str
OrderStatus                   str
Invoice                       str
CustomerID_clean              str
Country_clean                 str
StockCode                     str
Quantity_clean              int32
PromotionCode_clean           str
ProductNameClean_Final        str
ProductFamilyClean            str
TotalPriceGBP             float32
dtype: object
------------------------------
Description

,count,mean,std,min,25%,50%,75%,max
Quantity_clean,1067371.0,11.726951,188.302963,1.00,1.00,3.000000,10.000000,99999.000
TotalPriceGBP,1067371.0,139.320023,1749.570435,0.55,12.49,31.700001,97.360001,1456985.375

FIN----------------------------------------------------------------------------------------------------

In [200]:
duckdb.query("""
COPY (
    SELECT * FROM df_order_final
)
TO 'F_orders.parquet'
(FORMAT PARQUET)
""")

In [178]:
from IPython.display import display, HTML

# On stocke votre code HTML dans une variable (sous forme de texte multi-lignes)
html_code = """
 <div>

<style scoped>

    .dataframe tbody tr th:only-of-type {

        vertical-align: middle;

    }


    .dataframe tbody tr th {

        vertical-align: top;

    }


    .dataframe thead th {

        text-align: right;

    }

</style>

<table border="1" class="dataframe">

  <thead>

    <tr style="text-align: right;">

      <th></th>

      <th>StockCode</th>

      <th>ProductCategory_Propre</th>

      <th>ProductFamilyClean</th>

      <th>ProductNameClean_Final</th>

      <th>UnitPriceGBP_Propre</th>

      <th>UnitCostGBP_Propre</th>

    </tr>

  </thead>

  <tbody>

    <tr>

      <th>112</th>

      <td>21843</td>

      <td>kitchenware</td>

      <td>interior</td>

      <td>red retrospot cake stand</td>

      <td>32.139999</td>

      <td>21.290001</td>

    </tr>

    <tr>

      <th>252</th>

      <td>21843</td>

      <td>kitchen</td>

      <td>interior</td>

      <td>red retrospot cake stand</td>

      <td>32.139999</td>

      <td>15.679513</td>

    </tr>

    <tr>

      <th>1554</th>

      <td>21843</td>

      <td>kitchenware</td>

      <td>interior</td>

      <td>retro spot cake stand</td>

      <td>32.139999</td>

      <td>21.290001</td>

    </tr>

    <tr>

      <th>2229</th>

      <td>21843</td>

      <td>kitchen</td>

      <td>interior</td>

      <td>red retrospot cake stand</td>

      <td>32.139999</td>

      <td>21.290001</td>

    </tr>

    <tr>

      <th>2369</th>

      <td>21843</td>

      <td>kitchenware</td>

      <td>interior</td>

      <td>red retrospot cake stand</td>

      <td>32.139999</td>

      <td>15.679513</td>

    </tr>

    <tr>

      <th>4439</th>

      <td>21843</td>

      <td>kitchen</td>

      <td>interior</td>

      <td>retro spot cake stand</td>

      <td>32.139999</td>

      <td>21.290001</td>

    </tr>

    <tr>

      <th>4614</th>

      <td>21843</td>

      <td>other</td>

      <td>other</td>

      <td>broken</td>

      <td>8.420000</td>

      <td>3.570000</td>

    </tr>

    <tr>

      <th>6699</th>

      <td>21843</td>

      <td>other</td>

      <td>other</td>

      <td>smashed</td>

      <td>8.420000</td>

      <td>3.570000</td>

    </tr>

    <tr>

      <th>6976</th>

      <td>21843</td>

      <td>kitchenware</td>

      <td>interior</td>

      <td>retro spot cake stand</td>

      <td>43.640427</td>

      <td>21.290001</td>

    </tr>

    <tr>

      <th>9366</th>

      <td>21843</td>

      <td>other</td>

      <td>other</td>

      <td>damaged</td>

      <td>8.420000</td>

      <td>3.570000</td>

    </tr>

    <tr>

      <th>10360</th>

      <td>21843</td>

      <td>kitchenware</td>

      <td>interior</td>

      <td>red retrospot cake stand</td>

      <td>43.640427</td>

      <td>21.290001</td>

    </tr>

  </tbody>

</table>

</div> 
"""

# On demande à Python d'interpréter ce texte comme du vrai HTML
display(HTML(html_code))