In [11]:
from numpy import select
import pandas as pd
import duckdb
pd.set_option('display.max_columns', None)

df=duckdb.query("""
    select *
    From read_csv_auto('retailcorps.csv', all_varchar=true)
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [12]:
display(df.head(10))

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,ProductFamily,ProductNameClean,UnitPriceGBP,UnitCostGBP,CustomerSegment,CustomerType,LoyaltyProgram,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
0,1,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,13085.0,United Kingdom,SEASONAL,Seasonal,Occasions,15Cm Christmas Glass Ball 20 Lights,17.82,8.47,Regular,Small business,Bronze,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
1,2,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,13085.0,United Kingdom,HOME,Home decoration,Interior,Pink Cherry Lights,21.29,11.43,Regular,Small business,Bronze,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
2,3,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,13085.0,United Kingdom,HOME,Home decoration,Interior,White Cherry Lights,7.2,2.6,Regular,Small business,Bronze,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
3,4,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,13085.0,United Kingdom,HOME,Home decoration,Interior,"Record Frame 7"" Single Size",21.15,11.45,Regular,Small business,Bronze,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
4,5,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,13085.0,United Kingdom,OTHER,Other,Other,Strawberry Ceramic Trinket Box,12.74,5.85,Regular,Small business,Bronze,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
5,6,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,13085.0,United Kingdom,OTHER,Other,Other,Pink Doughnut Trinket Pot,10.44,6.29,Regular,Small business,Bronze,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
6,7,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,13085.0,United Kingdom,KITCHEN,Kitchenware,Interior,Save The Planet Mug,28.0,18.89,Regular,Small business,Bronze,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
7,8,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,13085.0,United Kingdom,OTHER,Other,Other,Fancy Font Home Sweet Home Doormat,10.26,3.96,Regular,Small business,Bronze,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
8,9,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,13085.0,United Kingdom,KITCHEN,Kitchenware,Interior,Cat Bowl,19.65,8.12,Regular,Small business,Bronze,Phone,Invoice,WH-UK-02,XMAS,0.15,Completed,9,Europe,Western Europe,GBP
9,10,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,13085.0,United Kingdom,KITCHEN,Kitchenware,Interior,"Dog Bowl , Chasing Ball Design",13.3,8.97,Regular,Small business,Bronze,Phone,Invoice,WH-UK-02,XMAS,0.15,Completed,9,Europe,Western Europe,GBP

In [7]:
duckdb.query("""
COPY(
    SELECT * FROM df
)
TO 'retailcorps.parquet'
(FORMAT PARQUET)
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [8]:
def explorer_dataset(dataset):
        print(f"Start {'-'*10} Pour ce dataset, la taille est de {dataset.shape} {'-'*10}")
        print('-'*30)
        display(dataset.head(3))
        print('-'*30)
        display(dataset.tail(3))
        print('-'*30)
        print(f"Présences de valeurs 'NaN'.")
        print(f"{dataset.isna().sum()}")
        display(dataset[dataset.isna().any(axis=1)])
        print('-'*30)
        print(f"Les doublons")
        print(f"{dataset.duplicated().sum()}")
        print('-'*30)
        print(f"Les types de données")
        print(f"{dataset.dtypes}")
        print('-'*30)
        print(f"Description")
        display(dataset.describe().T)
        print("FIN"+'-'*100)

In [9]:
explorer_dataset(df)

Start ---------- Pour ce dataset, la taille est de (1072707, 27) ----------
------------------------------

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,...,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
0,1,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,13085.0,United Kingdom,SEASONAL,Seasonal,...,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
1,2,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,13085.0,United Kingdom,HOME,Home decoration,...,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
2,3,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,13085.0,United Kingdom,HOME,Home decoration,...,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP

------------------------------

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,...,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
1072704,1033416,579188,22139,RETROSPOT TEA SET CERAMIC 11 PC,4,2011-11-28 15:34:00,12748.0,United Kingdom,KITCHEN,Kitchenware,...,Phone,Invoice,WH-UK-02,WELCOME10,0.1,Completed,15,Europe,Western Europe,GBP
1072705,1001514,576932,22086,PAPER CHAIN KIT 50'S CHRISTMAS,5,2011-11-17 11:12:00,15443.0,United Kingdom,SEASONAL,Seasonal,...,Marketplace,PayPal,WH-UK-02,NONE,0.0,Completed,9,Europe,Western Europe,GBP
1072706,1035637,579432,85203,HANGING WOOD AND FELT BUTTERFLY,8,2011-11-29 13:12:00,15311.0,United Kingdom,OTHER,Other,...,Online,Card,WH-UK-01,XMAS,0.15,Completed,11,Europe,Western Europe,GBP

------------------------------
Présences de valeurs 'NaN'.
OrderLineID                 0
Invoice                     0
StockCode                   0
Description             12993
Quantity                    0
InvoiceDate                 0
CustomerID             254201
Country                     0
ProductCategoryCode      3226
ProductCategory          4342
ProductFamily               0
ProductNameClean         4405
UnitPriceGBP                0
UnitCostGBP              1044
CustomerSegment             0
CustomerType                0
LoyaltyProgram              0
SalesChannel             4195
PaymentMethod               0
WarehouseID              1775
PromotionCode            1777
DiscountRate              636
OrderStatus              1334
DeliveryTime              815
Continent                   0
Region                      0
Currency                 1673
dtype: int64

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,...,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
31,32,489437,22143,CHRISTMAS CRAFT HEART DECORATIONS,6,2009-12-01 09:08:00,None,United Kingdom,SEASONAL,Seasonal,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
45,46,489437,21989,PACK OF 20 SKULL PAPER NAPKINS,12,2009-12-01 09:08:00,15362.0,United Kingdom,STATIONERY,None,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
120,121,489443,21035,SET/2 RED SPOTTY TEA TOWELS,12,2009-12-01 09:50:00,None,United Kingdom,KITCHEN,Kitchenware,...,Phone,Invoice,WH-UK-02,WELCOME10,0.1,Completed,2,Europe,Western Europe,GBP
126,127,489444,POST,POSTAGE,1,2009-12-01 09:55:00,12636.0,USA,OTHER,Other,...,None,Card,WH-NA-01,WELCOME10,0.1,Completed,4,North America,North America,USD
146,147,489446,21733,RED HANGING HEART T-LIGHT HOLDER,32,2009-12-01 10:06:00,13758.0,United Kingdom,HOME,None,...,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1072684,1034618,579297,21191,LARGE WHITE HONEYCOMB PAPER BELL,4,2011-11-29 11:23:00,None,United Kingdom,STATIONERY,Stationery,...,Marketplace,PayPal,WH-UK-02,NONE,0.0,Completed,14,Europe,Western Europe,GBP
1072693,1046889,580366,23393,HOME SWEET HOME CUSHION COVER,2,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
1072695,1040396,579751,22697,GREEN REGENCY TEACUP AND SAUCER,4,2011-11-30 14:46:00,None,United Kingdom,KITCHEN,Kitchenware,...,Marketplace,PayPal,WH-UK-02,WELCOME10,0.1,Completed,9,Europe,Western Europe,GBP
1072696,1039841,579694,21165,BEWARE OF THE CAT METAL SIGN,2,2011-11-30 14:11:00,None,United Kingdom,HOME,Home decoration,...,Store,Bank transfer,WH-UK-01,SPRING,0.05,Completed,15,Europe,Western Europe,GBP
1072697,1016248,578065,22807,SET OF 6 T-LIGHTS TOADSTOOLS,1,2011-11-22 15:41:00,None,United Kingdom,HOME,Home decoration,...,Phone,Invoice,WH-UK-02,NONE,0.0,Completed,15,Europe,Western Europe,GBP

------------------------------
Les doublons
5336
------------------------------
Les types de données
OrderLineID            object
Invoice                object
StockCode              object
Description            object
Quantity               object
InvoiceDate            object
CustomerID             object
Country                object
ProductCategoryCode    object
ProductCategory        object
ProductFamily          object
ProductNameClean       object
UnitPriceGBP           object
UnitCostGBP            object
CustomerSegment        object
CustomerType           object
LoyaltyProgram         object
SalesChannel           object
PaymentMethod          object
WarehouseID            object
PromotionCode          object
DiscountRate           object
OrderStatus            object
DeliveryTime           object
Continent              object
Region                 object
Currency               object
dtype: object
------------------------------
Description

,count,unique,top,freq
OrderLineID,1072707,1067371,1004179,2
Invoice,1072707,53628,537434,1355
StockCode,1072707,5619,85123A,5806
Description,1059714,9081,WHITE HANGING HEART T-LIGHT HOLDER,5806
Quantity,1072707,1150,1,294104
InvoiceDate,1072707,55180,2010-12-06 16:57:00,1337
CustomerID,818506,5942,17841.0,13009
Country,1072707,61,United Kingdom,974714
ProductCategoryCode,1069481,7,OTHER,453268
ProductCategory,1068365,14,Other,450561
ProductFamily,1072707,4,Other,454629
ProductNameClean,1068302,5620,White Hanging Heart T-Light Holder,5948
UnitPriceGBP,1072707,4348,14.47,6074
UnitCostGBP,1071663,2611,7.81,7656
CustomerSegment,1072707,4,VIP,449187
CustomerType,1072707,3,Retailer,531853
LoyaltyProgram,1072707,4,Gold,449187
SalesChannel,1068512,4,Marketplace,271975
PaymentMethod,1072707,4,PayPal,273029
WarehouseID,1070932,9,WH-UK-01,495246
PromotionCode,1070930,5,SPRING,222852
DiscountRate,1072071,6,0.05,222864
OrderStatus,1071373,3,Completed,942487
DeliveryTime,1071892,19,15,76253
Continent,1072707,6,Europe,1067806
Region,1072707,11,Western Europe,1054930
Currency,1071034,15,GBP,988647

FIN----------------------------------------------------------------------------------------------------